openapi: 3.0.1
info:
  title: DND Log Keeper API
  description: API to retrieve and manage D&D game logs.
  version: '1.0.0'
servers:
  - url: https://3d76391d-efdc-4c86-94fd-171415d3f221-00-2r6et1yal1hkt.kirk.replit.dev
paths:
  /logs:
    get:
      summary: Get all session logs
      operationId: getLogs
      responses:
        '200':
          description: A list of logs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Add a new session log
      operationId: addLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session:
                  type: string
                  example: "Session 1"
                notes:
                  type: string
                  example: "The party enters the dungeon."
      responses:
        '201':
          description: Log added